[tool.black]
skip-string-normalization = true
exclude = '(migrations)'

[tool.isort]
line_length = '88'
multi_line_output = '3'
include_trailing_comma = 'true'
combine_as_imports = '1'
known_firstparty = ['project']
known_third_party = ["dateutil", "markdown2", "pylint", "requests", "setuptools"]
sections = 'FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER'
